### ISSUE TITLE
https references

### ISSUE THREAD

**Issue by x110dc** [texastribune/faces-of-death-row#4]
Look at the developer console after visiting: https://apps.texastribune.org/death-row/

<img width="1428" alt="screenshot 2016-03-22 19 15 05" src="https://cloud.githubusercontent.com/assets/1091864/13971965/710d29aa-f062-11e5-9065-9193b8b43a31.png">

**Comment by joliesky** [comment]
I've made the changes and this should be ready to switch over to https!
